apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: tst-nginx
resources:
  - ../../base

namePrefix: tst-

configMapGenerator:
  - name: hello-world-cm
    literals:
      - ENVIRONMENT=test
