apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: prd-helloworld

namePrefix: prd-

generators:
  - chartInflator.yml

# helmCharts:
#   - name: rancher-demo
#     releaseName: prd-hello-world
#     valuesFile: values-prd.yaml
