apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-configs
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:MichaelTrip/gitops.git
    targetRevision: HEAD
    path: argocd-app-configs
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

---
