apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://10.99.98.200:6443
      - cluster: tst
        url: https://10.99.98.200:6443
      - cluster: acc
        url: https://kubernetes.default.svc
      - cluster: prd
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: '{{cluster}}-helloworld'
    spec:
      project: default
      source:
        repoURL: git@github.com:MichaelTrip/gitops.git
        targetRevision: HEAD
        path: 'apps/hello-world/overlays/{{cluster}}'
        plugin:
          name: kustomize-enable-helm
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true

      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-helloworld'
