
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: echo-environment
        image: busybox:latest
        command:
          - sh
          - -c
          - "sleep 3600"
        mounts:
          - name: workdir
            mountPath: "/workdir"
        envFrom:
        - configMapRef:
            name: hello-world-cm
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        mounts:
          - name: workdir
            mountPath: "/usr/share/nginx/html"
      volumeMounts:
        - name:  workdir
          emptyDir: {}
