apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx

resources:
  - deployment.yml
  - service.yml

commonLabels:
  appstack: nginx
  app: nginx

images:
- name: nginx
  newTag: latest


