apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: acc-helloworld

namePrefix: acc-

generators:
  - chartInflator.yml

# helmCharts:
#   - name: rancher-demo
#     releaseName: acc-hello-world
#     valuesFile: values-acc.yaml
