apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
resources:
  - ../../base

namespace: prd-nginx
namePrefix: prod-

configMapGenerator:
  - name: hello-world-cm
    behavior: replace
    literals:
      - ENVIRONMENT=production

