apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: prd-nginx
resources:
  - ../../base

namePrefix: prod-

configMapGenerator:
  - name: hello-world-cm
    literals:
      - ENVIRONMENT=production
