apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: acc-nginx
resources:
  - ../../base

namePrefix: acc-

configMapGenerator:
  - name: hello-world-cm
    literals:
      - ENVIRONMENT=acceptance

