apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: dev-rancher-demo
name: rancher-demo
repo: https://michaeltrip.github.io/helm-charts
version: 0.5.1
releaseName: dev-hello-world
values: values-dev.yml