apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: dev-helloworld


namePrefix: dev-

generators:
  - chartInflator.yml

# helmCharts:
#   - name: rancher-demo
#     releaseName: dev-hello-world
#     valuesFile: values-dev.yaml
