apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: tst-helloworld

namePrefix: tst-

generators:
  - chartInflator.yml

# helmCharts:
#   - name: rancher-demo
#     releaseName: tst-hello-world
#     valuesFile: values-tst.yaml
