apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: tst-helloworld
resources:
  - ../../base

namePrefix: tst-

helm:
  # Reference the chart from a Helm chart repository
  releases:
  - name: hello-world
    values:
      - values.yml
